spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/card_db?tinyInt1isBit=false&serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        #        show_sql: true
        #        highlight_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
      defer-datasource-initialization on: true

  data:
    redis:
      host: j10e101.p.ssafy.io
      port: 6380
      password: e101@ehfehswkq
      timeout: 3000

logging:
  level:
    com.ssafy.card: debug

jwt:
  secret: f35FS462GS54GADBNK32aXVH335YRGSF67JGH042FWD;

