spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/eureka_db?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
#    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
#        format_sql: true
        naming:
          physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy

  data:
    redis:
      host: localhost
      port: 6379
      password: 1234
      timeout: 3000

cloud:
  aws:
    credentials:
      accessKey:
      secretKey:
    region:
      static:
    s3:
      bucket: eureka_bucket

feign:
#  url: http://j10e101.p.ssafy.io:8001/card
  url: http://localhost:8001/card


jwt:
  secretKey: VYKlQrH0M4Gx7uUq7sXc7saINlUsZD9Vb6FZr5R4zoE
  accessTokenExpiration: 31536000000
  refreshTokenExpiration: 31536000000

logging:
  level:
    root: info
#    org.springframework:
#      web: debug
#      boot: debug
#      security: debug
    org.hibernate:
      sql: debug
      type.type.descriptor.sql: trace
    com.ssafy.eureka:
      domain: debug
      common: debug

springdoc:
  packages-to-scan:
    - com.ssafy.eureka.domain
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
#  api-docs:
#    path: /
  swagger-ui:
    display-request-duration: true
